# /stacks/staging/docker-compose.yml

services:
  snig-frontend:
    container_name: snig-web-demo
    build:
      # Ruta relativa para llegar desde /stacks/staging hasta /apps/snig-app
      context: ../../../app/FormatearCaravana/fonten_flutter
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    networks:
      - northcode-net
    environment:
      - NODE_ENV=${NODE_ENV}

  # NUEVA APP: Veterinaria Beltramelli (React)
  vet-core:
    container_name: vet-core-app
    build:
      # Ajustamos la ruta para que encuentre el repo de la veterinaria
      context: ../../../app/vet-core/apps/web-client
      dockerfile: dockerfile
    restart: unless-stopped
    networks:
      - northcode-net

networks:
  northcode-net:
    external: true # Le dice a Docker que use la red que creamos antes


    # /home/ary/Documentos/Project/northcode-infra/stacks/staging
    # /home/ary/Documentos/Project/apps/vet-core/apps/web-client
    # /home/ary/Documentos/Project/app/vet-core/apps/web-client